### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by cainejette**
First pass at dockerizing the things. 

includes the pipeline.yaml to make this build. 

There is a vdp concourse server at: https://35.199.175.103

### CODE REVIEW

**Comment by cainejette** [comment]
[ADD Concourse Build for VDP](https://trello.com/c/cpdiG8at/646-add-concourse-build-for-vdp)

**Comment by sarudak** [comment]
Looking at the changes here I'm not clear on why many of the changes have been made to the js files and how it relates to dockerization.

**Comment by baikon** [comment]
It looks like there was some code that had been merged from a feature branch in one of the js files. However, this branch still has conflicts that need to be resolved. I'll get on this with Rachel.

**Comment by sarudak** [comment]
This looks good

**Pull request merged**
